---
version: '3.4'
services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8000'
    - --scheme
    - http
    image: semitechnologies/weaviate:1.21.5
    restart: on-failure:0
    environment:
      IMAGE_INFERENCE_API: 'http://127.0.0.1:8000'
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/data'
      DEFAULT_VECTORIZER_MODULE: 'img2vec-neural'
      ENABLE_MODULES: 'img2vec-neural'
      CLUSTER_HOSTNAME: 'node1'
  i2v-neural:
    image: semitechnologies/img2vec-pytorch:resnet50
    environment:
      ENABLE_CUDA: '0'
  flask-app:
    build: .
    ports:
      - "80:5000"
    depends_on:
      - "weaviate"
      - "i2v-neural"
...
